### ISSUE TITLE
Implementation of SRL in Javascript

### ISSUE THREAD

**Issue by samelliott89** [SimpleRegex/SRL-PHP#18]
I'm currently building something quite complex with Regular Exp in JS and would love to have this implemented in JS.

**Comment by caoer** [comment]
👍

**Comment by KarimGeiger** [comment]
In the future, I'll be moving this project to [SimpleRegex/PHP](https://github.com/SimpleRegex/PHP), to have a better overview of everything to come. 

If someone wants to contribute an official JS version of this, please let me know. I'll then create a repository at [SimpleRegex/JavaScript](https://github.com/SimpleRegex/JavaScript) and give you permission on it.

**Comment by chriscorwin** [comment]
@KarimGeiger I'd love to help contribute to the JS one. :)

**Comment by KarimGeiger** [comment]
@chriscorwin awesome! I've created the project and gave you permissions. If you need any further help, let me know.

**Comment by chriscorwin** [comment]
@KarimGeiger Can I request that the project names not be simply "PHP" and "JavaScript", but rather something like "simple-regex-php" and "simple-regex-javascript"  ?

When I go to clone it, the idea of cloning into a directory named "JavaScript" hits a funny-sounding bell for me.

**Comment by KarimGeiger** [comment]
Yeah, that's a valid point... I guess it makes sense to call it SRL-[Language]

**Comment by SaptakS** [comment]
@KarimGeiger @chriscorwin I would also love to contribute in [SRL Javascript](https://github.com/SimpleRegex/SRL-JavaScript).

**Comment by jsenjoy** [comment]
@KarimGeiger @chriscorwin I wanna know how is about the progress of SRL Javascript, and if I can help to make contribute.

**Comment by KarimGeiger** [comment]
@jsenjoy looks like there isn't any progress made yet :( I've added you to the team and gave you access to the repository. Feel free to join us. I'd love to see a JS implementation for https://simple-regex.com as well. Would make it easier than to always call an API.

If you'd like me to add you to the Slack team as well, just leave me a note.

**Comment by jsenjoy** [comment]
@KarimGeiger Yeah, plz add me to the Slack.

**Comment by KarimGeiger** [comment]
The [JavaScript repository](https://github.com/SimpleRegex/SRL-JavaScript) now contains a working port of SRL. Great work @jsenjoy!
