### ISSUE TITLE
Implementation of SRL in Python

### ISSUE THREAD

**Issue by mhbashari** [SimpleRegex/SRL-PHP#22]

**Comment by KarimGeiger** [comment]
In the future, I'll be moving this project to [SimpleRegex/PHP](https://github.com/SimpleRegex/PHP), to have a better overview of everything to come. 

If someone wants to contribute an official Python version of this, please let me know. I'll then create a repository at [SimpleRegex/Python](https://github.com/SimpleRegex/Python) and give you permission on it.

**Comment by mhbashari** [comment]
I can do it.

**Comment by KarimGeiger** [comment]
That would be awesome. Thanks for that! I've create the repository and granted you write permission. If you need any further help, let me know.

**Comment by mhbashari** [comment]
Thank you...

**Comment by Saluev** [comment]
Whoa, we could make a competition on this

**Comment by SaptakS** [comment]
@KarimGeiger @mhbashari  I would also love to contribute in [SRL Python](https://github.com/SimpleRegex/SRL-Python).

**Comment by KarimGeiger** [comment]
@SaptakS thanks! I've added you to both teams and sent you an invitation to the SRL slack team.

**Comment by SaptakS** [comment]
@KarimGeiger Thanks. :smile:

**Comment by Saluev** [comment]
By the way, when will the language specification alpha be available?

**Comment by KarimGeiger** [comment]
I'm not sure. I'll start working on it this weekend, so it might be done next week, but I can't promise anything. Anyhow, I consider the language specification a high priority, so it shouldn't take forever to be done.

**Comment by KarimGeiger** [comment]
Thanks to @soasme we now have a working Python implementation of SRL. Great work of all of you, you're quite awesome!

I've updated https://simple-regex.com to point to this repository as well, to give the visitors a choice of what implementation to choose.
